dataset: crowdhuman
crowdhuman_train_split: train_val
train_split: train
val_split: val

frame_dropout_prob: 0.0
sequence_frames: null # We pick same img buy apply a different transformation

# Training
epochs: 90
lr_drop: 60

# Evaluation
max_num_of_frames_lookback: 1