model: perceiver

# Backbone parameters
backbone: "resnet50"  # Name of the convolutional backbone to use
# Use feature output from resnet backbone at intermediate layer (layer0, layer1, layer2)
interm_layer: null

# Perceiver model parameters
num_freq_bands: 6  # Number of frequency bands
max_freq: 10  # Maximum frequency, depending on data granularity
enc_layers: 1  # Number of encoding layers in the transformer
num_queries: 100  # Number of latents/queries/centroids
hidden_dim: 256  # Latent dimension size
enc_nheads_cross: 8  # Number of cross attention heads in the perceiver encoder
nheads: 1  # Number of heads for latent self-attention
dropout: 0.0  # Dropout rate in the transformer
self_per_cross_attn: 8  # Number of self-attention blocks per cross attention

# Dataset
frame_dropout_prob: 0.0

# Training
track_query_false_positive_prob: 0.0
track_query_false_negative_prob: 0.0
val_interval: 1 # Evaluate on every epoch on validation set

wandb_project: 'perceiver_track'